# Generated by Django 3.0.4 on 2020-03-31 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morocco_mapping', '0002_auto_20200331_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='boundarycenter',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
